disabled_rules:
  - trailing_whitespace
  - identifier_name
  - inclusive_language
  - for_where
  - type_name
  - block_based_kvo
  - empty_count
opt_in_rules:
  - empty_string
excluded:
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib
  - .build
weak_delegate:
    excluded: ".*Test\\.swift" #regex path to your tests folder
line_length:
    warning: 500
    error: 1500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 3000
    error: 5000
function_parameter_count:
    warning: 10
    error: 20
type_body_length:
    warning: 2000
    error: 5000
file_length:
    warning: 3000
    error: 5000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 200
    error: 1000
reporter: "xcode"
